one more time.    public breeds:any = {}; because although working locally, not building on heroku.  but this type declaration is removing the errors on heroku build.  this is the last error that I see in the logs - ERROR in src/app/search/search.component.html(6,13): : Property 'message' does not exist on type 'any[]'.